import { ALL_PERMISSIONS, PERMISSION_GROUPS } from './permissions'

// Default system roles
export const DEFAULT_ROLES = {
  SUPER_ADMIN: 'super_admin',
  ADMIN: 'admin',
  BRANCH_MANAGER: 'branch_manager',
  HR_MANAGER: 'hr_manager',
  FINANCE_MANAGER: 'finance_manager',
  PROCUREMENT_MANAGER: 'procurement_manager',
  INVENTORY_MANAGER: 'inventory_manager',
  ACCOUNTANT: 'accountant',
  HR_OFFICER: 'hr_officer',
  PROCUREMENT_OFFICER: 'procurement_officer',
  INVENTORY_OFFICER: 'inventory_officer',
  EMPLOYEE: 'employee',
} as const

// Role permissions mapping
export const ROLE_PERMISSIONS = {
  [DEFAULT_ROLES.SUPER_ADMIN]: Object.values(ALL_PERMISSIONS),
  
  [DEFAULT_ROLES.ADMIN]: [
    ...PERMISSION_GROUPS.AUTHENTICATION,
    ...PERMISSION_GROUPS.BRANCH_MANAGEMENT,
    ...PERMISSION_GROUPS.WORKFLOWS,
    ...PERMISSION_GROUPS.REPORTING,
    ...PERMISSION_GROUPS.SETTINGS,
    ALL_PERMISSIONS.VIEW_NOTIFICATIONS,
    ALL_PERMISSIONS.SEND_SYSTEM_NOTIFICATIONS,
  ],
  
  [DEFAULT_ROLES.BRANCH_MANAGER]: [
    ALL_PERMISSIONS.VIEW_USERS,
    ALL_PERMISSIONS.VIEW_BRANCHES,
    ...PERMISSION_GROUPS.PROCUREMENT,
    ...PERMISSION_GROUPS.INVENTORY,
    ...PERMISSION_GROUPS.PAYROLL,
    ...PERMISSION_GROUPS.ACCOUNTING,
    ...PERMISSION_GROUPS.WORKFLOWS,
    ...PERMISSION_GROUPS.REPORTING,
    ...PERMISSION_GROUPS.DOCUMENTS,
    ALL_PERMISSIONS.VIEW_NOTIFICATIONS,
    ALL_PERMISSIONS.MANAGE_NOTIFICATION_PREFERENCES,
  ],
  
  [DEFAULT_ROLES.HR_MANAGER]: [
    ALL_PERMISSIONS.VIEW_USERS,
    ALL_PERMISSIONS.MANAGE_USERS,
    ALL_PERMISSIONS.RESET_USER_PASSWORD,
    ...PERMISSION_GROUPS.PAYROLL,
    ALL_PERMISSIONS.APPROVE_WORKFLOW_TASKS,
    ALL_PERMISSIONS.REJECT_WORKFLOW_TASKS,
    ALL_PERMISSIONS.VIEW_REPORTS,
    ALL_PERMISSIONS.CREATE_REPORTS,
    ALL_PERMISSIONS.EXPORT_REPORTS,
    ...PERMISSION_GROUPS.DOCUMENTS,
    ALL_PERMISSIONS.VIEW_NOTIFICATIONS,
    ALL_PERMISSIONS.MANAGE_NOTIFICATION_PREFERENCES,
  ],
  
  [DEFAULT_ROLES.FINANCE_MANAGER]: [
    ...PERMISSION_GROUPS.ACCOUNTING,
    ALL_PERMISSIONS.PROCESS_PAYMENTS,
    ALL_PERMISSIONS.MANAGE_INVOICES,
    ALL_PERMISSIONS.APPROVE_PAYROLL,
    ALL_PERMISSIONS.APPROVE_WORKFLOW_TASKS,
    ALL_PERMISSIONS.REJECT_WORKFLOW_TASKS,
    ALL_PERMISSIONS.VIEW_REPORTS,
    ALL_PERMISSIONS.CREATE_REPORTS,
    ALL_PERMISSIONS.EXPORT_REPORTS,
    ...PERMISSION_GROUPS.DOCUMENTS,
    ALL_PERMISSIONS.VIEW_NOTIFICATIONS,
    ALL_PERMISSIONS.MANAGE_NOTIFICATION_PREFERENCES,
  ],
  
  [DEFAULT_ROLES.PROCUREMENT_MANAGER]: [
    ...PERMISSION_GROUPS.PROCUREMENT,
    ALL_PERMISSIONS.VIEW_INVENTORY,
    ALL_PERMISSIONS.APPROVE_WORKFLOW_TASKS,
    ALL_PERMISSIONS.REJECT_WORKFLOW_TASKS,
    ALL_PERMISSIONS.VIEW_REPORTS,
    ALL_PERMISSIONS.CREATE_REPORTS,
    ALL_PERMISSIONS.EXPORT_REPORTS,
    ...PERMISSION_GROUPS.DOCUMENTS,
    ALL_PERMISSIONS.VIEW_NOTIFICATIONS,
    ALL_PERMISSIONS.MANAGE_NOTIFICATION_PREFERENCES,
  ],
  
  [DEFAULT_ROLES.INVENTORY_MANAGER]: [
    ...PERMISSION_GROUPS.INVENTORY,
    ALL_PERMISSIONS.RECEIVE_GOODS,
    ALL_PERMISSIONS.VIEW_PURCHASE_ORDERS,
    ALL_PERMISSIONS.APPROVE_WORKFLOW_TASKS,
    ALL_PERMISSIONS.REJECT_WORKFLOW_TASKS,
    ALL_PERMISSIONS.VIEW_REPORTS,
    ALL_PERMISSIONS.CREATE_REPORTS,
    ALL_PERMISSIONS.EXPORT_REPORTS,
    ...PERMISSION_GROUPS.DOCUMENTS,
    ALL_PERMISSIONS.VIEW_NOTIFICATIONS,
    ALL_PERMISSIONS.MANAGE_NOTIFICATION_PREFERENCES,
  ],
  
  [DEFAULT_ROLES.ACCOUNTANT]: [
    ALL_PERMISSIONS.VIEW_ACCOUNTS,
    ALL_PERMISSIONS.CREATE_JOURNAL_ENTRIES,
    ALL_PERMISSIONS.VIEW_JOURNAL_ENTRIES,
    ALL_PERMISSIONS.VIEW_TRIAL_BALANCE,
    ALL_PERMISSIONS.VIEW_FINANCIAL_STATEMENTS,
    ALL_PERMISSIONS.MANAGE_INVOICES,
    ALL_PERMISSIONS.VIEW_REPORTS,
    ALL_PERMISSIONS.CREATE_REPORTS,
    ALL_PERMISSIONS.EXPORT_REPORTS,
    ALL_PERMISSIONS.VIEW_DOCUMENTS,
    ALL_PERMISSIONS.UPLOAD_DOCUMENTS,
    ALL_PERMISSIONS.VIEW_NOTIFICATIONS,
    ALL_PERMISSIONS.MANAGE_NOTIFICATION_PREFERENCES,
  ],
  
  [DEFAULT_ROLES.HR_OFFICER]: [
    ALL_PERMISSIONS.VIEW_USERS,
    ALL_PERMISSIONS.VIEW_PAYROLL,
    ALL_PERMISSIONS.MANAGE_EMPLOYEES,
    ALL_PERMISSIONS.GENERATE_PAYSLIPS,
    ALL_PERMISSIONS.VIEW_PAYSLIPS,
    ALL_PERMISSIONS.DOWNLOAD_PAYSLIPS,
    ALL_PERMISSIONS.VIEW_REPORTS,
    ALL_PERMISSIONS.CREATE_REPORTS,
    ALL_PERMISSIONS.VIEW_DOCUMENTS,
    ALL_PERMISSIONS.UPLOAD_DOCUMENTS,
    ALL_PERMISSIONS.VIEW_NOTIFICATIONS,
    ALL_PERMISSIONS.MANAGE_NOTIFICATION_PREFERENCES,
  ],
  
  [DEFAULT_ROLES.PROCUREMENT_OFFICER]: [
    ALL_PERMISSIONS.CREATE_PURCHASE_REQUEST,
    ALL_PERMISSIONS.VIEW_PURCHASE_REQUESTS,
    ALL_PERMISSIONS.CREATE_PURCHASE_ORDER,
    ALL_PERMISSIONS.VIEW_PURCHASE_ORDERS,
    ALL_PERMISSIONS.MANAGE_VENDORS,
    ALL_PERMISSIONS.RECEIVE_GOODS,
    ALL_PERMISSIONS.VIEW_INVENTORY,
    ALL_PERMISSIONS.VIEW_REPORTS,
    ALL_PERMISSIONS.VIEW_DOCUMENTS,
    ALL_PERMISSIONS.UPLOAD_DOCUMENTS,
    ALL_PERMISSIONS.VIEW_NOTIFICATIONS,
    ALL_PERMISSIONS.MANAGE_NOTIFICATION_PREFERENCES,
  ],
  
  [DEFAULT_ROLES.INVENTORY_OFFICER]: [
    ALL_PERMISSIONS.VIEW_INVENTORY,
    ALL_PERMISSIONS.MANAGE_ITEMS,
    ALL_PERMISSIONS.MANAGE_CATEGORIES,
    ALL_PERMISSIONS.ADJUST_STOCK,
    ALL_PERMISSIONS.VIEW_STOCK_TRANSACTIONS,
    ALL_PERMISSIONS.MANAGE_STOCK_LEVELS,
    ALL_PERMISSIONS.RECEIVE_GOODS,
    ALL_PERMISSIONS.VIEW_PURCHASE_ORDERS,
    ALL_PERMISSIONS.VIEW_REPORTS,
    ALL_PERMISSIONS.VIEW_DOCUMENTS,
    ALL_PERMISSIONS.UPLOAD_DOCUMENTS,
    ALL_PERMISSIONS.VIEW_NOTIFICATIONS,
    ALL_PERMISSIONS.MANAGE_NOTIFICATION_PREFERENCES,
  ],
  
  [DEFAULT_ROLES.EMPLOYEE]: [
    ALL_PERMISSIONS.VIEW_PAYSLIPS,
    ALL_PERMISSIONS.DOWNLOAD_PAYSLIPS,
    ALL_PERMISSIONS.CREATE_PURCHASE_REQUEST,
    ALL_PERMISSIONS.VIEW_PURCHASE_REQUESTS, // Only their own
    ALL_PERMISSIONS.VIEW_NOTIFICATIONS,
    ALL_PERMISSIONS.MANAGE_NOTIFICATION_PREFERENCES,
  ],
} as const

// Role hierarchy (higher number = more authority)
export const ROLE_HIERARCHY = {
  [DEFAULT_ROLES.SUPER_ADMIN]: 100,
  [DEFAULT_ROLES.ADMIN]: 90,
  [DEFAULT_ROLES.BRANCH_MANAGER]: 80,
  [DEFAULT_ROLES.HR_MANAGER]: 70,
  [DEFAULT_ROLES.FINANCE_MANAGER]: 70,
  [DEFAULT_ROLES.PROCUREMENT_MANAGER]: 70,
  [DEFAULT_ROLES.INVENTORY_MANAGER]: 70,
  [DEFAULT_ROLES.ACCOUNTANT]: 60,
  [DEFAULT_ROLES.HR_OFFICER]: 50,
  [DEFAULT_ROLES.PROCUREMENT_OFFICER]: 50,
  [DEFAULT_ROLES.INVENTORY_OFFICER]: 50,
  [DEFAULT_ROLES.EMPLOYEE]: 10,
} as const

// Role descriptions
export const ROLE_DESCRIPTIONS = {
  [DEFAULT_ROLES.SUPER_ADMIN]: 'Full system access with all permissions',
  [DEFAULT_ROLES.ADMIN]: 'System administration and user management',
  [DEFAULT_ROLES.BRANCH_MANAGER]: 'Manages all operations within a branch',
  [DEFAULT_ROLES.HR_MANAGER]: 'Manages human resources and payroll',
  [DEFAULT_ROLES.FINANCE_MANAGER]: 'Manages financial operations and accounting',
  [DEFAULT_ROLES.PROCUREMENT_MANAGER]: 'Manages procurement processes and vendor relations',
  [DEFAULT_ROLES.INVENTORY_MANAGER]: 'Manages inventory and stock operations',
  [DEFAULT_ROLES.ACCOUNTANT]: 'Handles accounting entries and financial records',
  [DEFAULT_ROLES.HR_OFFICER]: 'Assists with HR operations and employee management',
  [DEFAULT_ROLES.PROCUREMENT_OFFICER]: 'Handles purchase requests and vendor communications',
  [DEFAULT_ROLES.INVENTORY_OFFICER]: 'Manages stock levels and inventory transactions',
  [DEFAULT_ROLES.EMPLOYEE]: 'Basic employee access to personal information and requests',
} as const

export type RoleName = typeof DEFAULT_ROLES[keyof typeof DEFAULT_ROLES]